name: rss_dart
version: 1.0.10
description: rss_dart is a rss parser for RSS1.0/RSS2.0/Atom. This library is forked from webfeed https://github.com/witochandra/webfeed and dart_rss.
homepage: https://github.com/ubuntu-flutter-community/rss.dart

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  xml: ^6.5.0
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0
