name: rss_dart
version: 1.0.3
description: dart-rss is a rss parser for RSS1.0/RSS2.0/Atom. It also support Dublin-Core, Content, Syndication additional modules. This libary is forked from webfeed(https://github.com/witochandra/webfeed).
homepage: https://github.com/sudame/dart-rss
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  xml: ^6.3.0
  http: ^0.13.0
  intl: ^0.18.0

dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0

